environment:

  matrix:

    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python

    - PYTHON: "C:\\C:\Python26-x64"
      TOX_ENV: "py26"

    - PYTHON: "C:\\Python27-x64"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python33-x64"
      TOX_ENV: "py33"

    - PYTHON: "C:\\Python34-x64"
      TOX_ENV: "py34"

    - PYTHON: "C:\\Python35-x64"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36-x64"
      TOX_ENV: "py36"

install:
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -e %TOX_ENV%"
